language: cpp

arch:
  - amd64
  - arm64
  - armf
  - armv7

compiler:
  - gcc

before_script:
  - sudo apt-get install -y libboost-all-dev libpcap-dev
  - mkdir build
  - cd build
  - cmake ..

script: make && cpack

deploy:
  provider: releases
  api_key: "6a77e41a0a1834e8bf4fde7b15326c9a99189fb7"
  file_glob: true
  file: "build/*.deb"
  skip_cleanup: true
  on:
    tags: true
