language: cpp

arch:
  - amd64
  - arm64
  - armf
  - armv7

compiler:
  - gcc

before_script:
  - sudo apt-get install -y libboost-all-dev libpcap-dev
  - mkdir build
  - cd build
  - cmake ..

script: make && cpack
