name: build-debs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install-build-deps
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static
    - name: compile-kali-rolling
      run: |
        sudo ./scripts/mkdeb
        mkdir -p deb/kali-rolling
        sudo mv build/*.deb deb/kali-rolling
        sudo rm -rf build
    - name: compile-bionic-armhf
      run: |
        docker run -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static -v`pwd`:/mnt --rm arm32v7/ubuntu:bionic /bin/bash -c "cd /mnt; scripts/mkdeb"
        mkdir deb/bionic-armhf
        sudo mv build/*.deb deb/bionic-armhf
        sudo rm -rf build
    - name: compile-buster-armhf
      run: |
        docker run -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static -v`pwd`:/mnt --rm yummygooey/raspbian-buster /bin/bash -c "cd /mnt; scripts/mkdeb"
        mkdir deb/buster-armhf
        sudo mv build/*.deb deb/buster-armhf
        sudo rm -rf build
    - name: compile-bionic-arm64
      run: |
        docker run -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static -v`pwd`:/mnt --rm arm64v8/ubuntu:bionic /bin/bash -c "cd /mnt; scripts/mkdeb"
        mkdir deb/bionic-arm64
        sudo mv build/*.deb deb/bionic-arm64
        sudo rm -rf build
    - name: compile-buster-arm64
      run: |
        docker run -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static -v`pwd`:/mnt --rm arm64v8/debian:busterr /bin/bash -c "cd /mnt; scripts/mkdeb"
        mkdir deb/stretch-armhf
        sudo mv build/*.deb deb/stretch-armhf
        sudo rm -rf build
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: deb-files
        path: deb
