name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install-dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-all-dev libpcap-dev cmake
    - name: cmake-configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=/ ..
    - name: build
      run: |
        cd build
        make
    - name: create-deb
      run: |
        cd build
        cpack
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: my-artifact
        path: build/wifibroadcast_bridge-0.1.0.deb
